---

- name: Ensure AppArmor knows about our new config file, the socket, and some log files it tries to create
  ansible.builtin.blockinfile:
    path: /etc/apparmor.d/local/php-fpm
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{php_fpm_pool}}"
    state: present
    block: |
      /var/log/php-fpm/{{php_fpm_pool}}.access.log rw,
      /var/log/php-fpm/{{php_fpm_pool}}.log.slow rw,
      /var/log/{{php_fpm_pool}}.log rw,
      @{run}/php{,-fpm}/{{php_fpm_pool}}.pid rw,
      @{run}/{{php_fpm_pool}}.pid rw,
      @{run}/php{,-fpm}/{{php_fpm_pool}}.sock rwlk,
  tags: ['apparmor']

- name: Ensure AppArmor is reloaded
  systemd:
    name: apparmor
    state: restarted
  tags: ['apparmor']
