---
- name: Converge
  hosts: all
  tasks:
    - name: Install nginx
      package:
        name: nginx
        state: present
    - name: Enable nginx
      systemd:
        name: nginx
        state: started
        enabled: true
    - name: "Include geekoops-php-fpm"
      include_role:
        name: "geekoops-php-fpm"
    ## Setup test enviroment
    # Smoke test for nginx
    - name: Deploy index.html
      copy:
        content: |
          This page is a stub.
        dest: "{{www_dir}}/index.html"
        group: "root"
        owner: "root"
        mode: 0644
      register: deployed
    # We setup phpinfo.php and configure nginx to use php for *.php files
    - name: Deploy phpinfo script
      copy:
        content: |
          <?php phpinfo(); phpinfo(INFO_MODULES); ?>
        dest: "{{www_dir}}/phpinfo.php"
        group: "{{phpgroup}}"
        owner: "{{phpuser}}"
        mode: 0754
      register: deployed
    - name: Deploy nginx configuration
      copy:
        content: |
              server {
                  listen 80 default_server;
                  listen [::]:80 default_server;
                  root "{{ www_dir }}";
                  index index.html index.htm;
                  location / {
                      try_files $uri $uri/ =404;
                  }
                  location ~ \.php$ {
                      fastcgi_pass   unix:/run/php-fpm/www.sock;
                      fastcgi_index  index.php;
                      fastcgi_param  SCRIPT_FILENAME $request_filename;
                      include        fastcgi_params;
                  }
              }
        dest: "{{vhosts_dir}}/default.conf"
        owner: root
        group: root
        mode: 0644
      when: deployed.changed and deploy_nginx_config == true
    - name: Ensure nginx is in php group
      user:
        name: "{{nginxuser}}"
        groups: ["{{phpgroup}}"]
        append: true
    # Restart of nginx is required for them to have the new configuration
    - name: Restart nginx
      systemd:
        name: nginx
        state: restarted
      when: deployed.changed
