---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: leap15_4
    image: registry.opensuse.org/opensuse/leap:15.4
    dockerfile: Dockerfile.leap15_4
    command: ${MOLECULE_DOCKER_COMMAND:-"/usr/sbin/init"}
    privileged: true
    cgroupns: host
    tmpfs:
      - /run
      - /tmp
provisioner:
  name: ansible
  inventory:
    host_vars:
      leap15_4:
        www_dir: "/srv/www/htdocs"
        vhosts_dir: "/etc/nginx/vhosts.d"
        phpgroup: www
        phpuser: wwwrun
        nginxuser: nginx
        nginxgroup: nginx
        deploy_nginx_config: true
verifier:
  name: testinfra
